# Generated by Django 5.0.4 on 2024-05-16 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_created_at_alter_product_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
