# Generated by Django 4.2.2 on 2024-06-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('unpublished', 'Can unpublished')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
